### PR TITLE
fix: new percy sizes

### PR DESCRIPTION
**Pull request by cooper667**
Add default Percy sizes

### CODE REVIEW

**Review by ChasNelson1990 — APPROVED** [review]
I presume this moves them out from wherever I put them?

**Comment by ChasNelson1990** [comment]
Oooh, are there no branch rules yet?

**Comment by cooper667** [comment]
You're lucky there's a PR. We're upto v5.0.1 with me just commiting to `main`

**Comment by cooper667** [comment]
> I presume this moves them out from wherever I put them?

I think we are using the default unless there is a percy.yml file, so we don't need one of those in any repos where we use this for the screenshots

**Pull request merged**
